branch-defaults:
  master:
    environment: weather-app
    group_suffix: null
global:
  application_name: weather-app-prod-env
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
